### ISSUE TITLE
建议限制容器日志大小

### ISSUE THREAD

**Issue by uxh** [krwu/lhmon#2]
现在的默认配置是否是未限制？是否可以考虑限制下日志大小，避免容器运行时间太长后，日志文件过大。
参考配置：
```
logging:
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "5"
```
